

server:
  port: 8701

spring:
  application:
    name: 250RM

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # http://service01:spdb1234@localhost:8761/eureka/
